### ISSUE TITLE
Lint against explicit use of @babel/preset-env and @babel/preset-react in liferay-portal

### ISSUE THREAD

**Issue by wincent** [liferay/eslint-config-liferay#130]
When https://github.com/wincent/liferay-portal/pull/120 (or some iteration of it) gets merged, those presets will be the default, so we should lint against them being used needlessly in .babelrc files in liferay-portal, much like we do for .eslintrc.js files using [the `liferay-portal/no-explicit-extend` rule](https://github.com/liferay/eslint-config-liferay/blob/master/plugins/eslint-plugin-liferay-portal/docs/rules/no-explicit-extend.md).

One gotcha to bear in mind: "no-explicit-extend" works because our ESLint config lives in JS files. In contrast, our Babel config is JSON inside `.babelrc` files, which won't be processed automatically by ESLint. I don't know if we have any impediments to moving those files over to JS (we're using [cosmiconfig](https://www.npmjs.com/package/cosmiconfig) to read config files in liferay-npm-scripts), and [the Babel docs](https://babeljs.io/docs/en/configuration) are a bit ambiguous:

> You can also write `babel.config.json` and `.babelrc.json` files using JavaScript

(Sure does sound like they're telling you to put `module.exports = {}` JS inside a file with ` .json` extension... And their docs don't mention the `.js` extension at all. 🤔)

**Comment by wincent** [comment]
Found [this other page](https://babeljs.io/docs/en/config-files/) which documents `.js` config files.

**Comment by jbalsas** [comment]
We could sneakily start linting and formatting `.babelrc` files, couldn't we?

**Comment by wincent** [comment]
Yeah, in my testing, it seems we can rename them to `.babelrc.js` and get linting/formatting for free. And it looks like it would be pretty cheap to add a quick check for files that sneak in with the old name (`.babelrc`).
