### ISSUE TITLE
Enforce indentation?

### ISSUE THREAD

**Issue by robframpton** [liferay/eslint-config-liferay#4]
Do we want to consider enforcing indentation using the [indet](http://eslint.org/docs/rules/indent) rule?

I've noticed a few metal-* projects that have mixed tabs and spaces, it would be nice to automate that standard. The google doc we have that details our coding standards states that we want to use tabs, is that still current?

**Comment by eduardolundgren** [comment]
I am still not sure about using tabs, spaces makes more sense for many different reasons like alignment and visualization consistency.

**Comment by jbalsas** [comment]
Hey @Robert-Frampton, @eduardolundgren, this should be enforced by applying the formatting guidelines (via prettier) already merged in the `format` task in `gulp-metal`.

https://github.com/metal/gulp-metal/blob/master/lib/tasks/index.js#L38-L44

We should start applying it to enforce consistency. If we want to switch to spaces later, we can do it easily now...

**Comment by jbalsas** [comment]
I'm closing this, since we might want to leave stylistic issues for the formatter.
