### ISSUE TITLE
What are the benefits of allowing unused function params?

### ISSUE THREAD

**Issue by ipeychev** [liferay/eslint-config-liferay#5]
Hello,

Currently, it is allowed a function to have unused params. This is how the rule currently looks like:
```
"no-unused-vars": [
  2,
  {
    "args": "none"
  }
]
```
What are the benefits of that? In most cases, this may lead to bad API design and misleading source code. What about restoring this rule to the default option in ESLint? It is:
```
"no-unused-vars": [
  2,
  {
    "args": "after-used"
  }
]
```

Thanks,

**Comment by jbalsas** [comment]
Hey @ipeychev, as far as I can tell, `after-used` still allows unused params since it only checks the last one, right? 

This setting was overridden by google, I would guess, to make it easier to adopt in existing codebases. I would vote to set it to `"args": "all"` and disable it if necessary when introducing it into the projects until they are clean.

What do you think?

**Comment by jbalsas** [comment]
I guess one possible use case of `"args": "none"` is to allow refactoring an API without introducing breaking changes. That way, if you stop using params, you can still take the one needed without forcing everyone to upgrade.

I'm not saying it is useful or nice, just trying to answer your question 😉

**Comment by ipeychev** [comment]
I think "args": "after-used" is the golden middle and this is the right choice for both writing new code and applying the settings to existing codebase (aka ESlint were correct to set it like this by default).
To allow unused params in function calls, but to forbid unused variables inside functions just doesn't make sense - this only will lead to bad function signatures.

**Comment by jbalsas** [comment]
Hey @ipeychev, I'm fine setting it to the ESlint default, really :)

Also, @eduardolundgren, can we transfer this to the liferay org?
