### ISSUE TITLE
Add "sort-keys" rule

### ISSUE THREAD

**Issue by wincent** [liferay/eslint-config-liferay#52]
Requested here: https://github.com/brianchandotcom/liferay-portal/pull/75764#issuecomment-511905751

This is straightforwardly achievable with the [sort-keys](https://eslint.org/docs/rules/sort-keys) rule. Object property order *could* in theory matter, but I think it's quite unlikely that our projects rely on it anywhere, especially because the rule doesn't sort across spreads:

```
// This rule does not report unsorted properties that are separated by a spread property.
let obj = {b: 1, ...c, a: 2};
```

We're already [using `sort-keys` in Clay](https://github.com/liferay/clay/blob/ee799051689871e07a520385bb8367ba55d5bf27/.eslintrc.json#L51-L57) to good effect.

**Comment by jbalsas** [comment]
Done via https://github.com/liferay/eslint-config-liferay/pull/63
