### ISSUE TITLE
feat: enforce deprecation notices to contain version names

### ISSUE THREAD

**Issue by jbalsas** [liferay/eslint-config-liferay#55]
As requested at https://github.com/brianchandotcom/liferay-portal/pull/76327#issuecomment-516611349, when tagging classes/methods with the `@deprecated` annotation, we should always include the version names of the product.

> ```
> /**
>  * The Storage Formatter Utility
>  *
>  * @deprecated since 7.3, replaced by Liferay.Util.formatStorage
>  * @module liferay-storage-formatter
>  */
> ```
> 
> Can you SF enforce the versions so they contain Athanasius /Mueller etc. Thx!

**Comment by wincent** [comment]
Here's [another example](https://github.com/brianchandotcom/liferay-portal/commit/dea258f5334414d9f38c59ea7112244f4f5da3f2):

Incorrect code:

```js
/**
 * @deprecated as of 7.3 - use `window.innerWidth` instead
 */
```

Correct code:

```js
/**
 * @deprecated As of Athanasius (7.3.x), replaced by `window.innerWidth`
 */
```

**Comment by wincent** [comment]
Examples showing valid version specifiers from liferay-portal:

```
* @deprecated As of Wilberforce (7.0.x)
* @deprecated As of Wilberforce (7.0.x), replaced by {@link
* @deprecated As of Wilberforce (7.0.x), with no direct replacement
* @deprecated As of Judson (7.1.x)
* @deprecated As of Judson (7.1.x), replaced by {@link
* @deprecated As of Judson (7.1.x), with no direct replacement
* @deprecated As of Mueller (7.2.x)
* @deprecated As of Mueller (7.2.x), replaced by {@link
* @deprecated As of Mueller (7.2.x), with no direct replacement
* @deprecated As of Athanasius (7.3.x)
* @deprecated As of Athanasius (7.3.x), replaced by {@link
* @deprecated As of Athanasius (7.3.x), with no direct replacement
```
