### ISSUE TITLE
Add "object-shorthand" rule

### ISSUE THREAD

**Issue by wincent** [liferay/eslint-config-liferay#59]
I don't have a link for this one, but via @jbalsas, Brian likes the shorthand, and we can enforce it with:

https://eslint.org/docs/rules/object-shorthand

**Comment by jbalsas** [comment]
It seems `object-shorthand` is already applied to both our `liferay` and our `portal` configs at https://github.com/liferay/eslint-config-liferay/blob/master/index.js#L30
