### ISSUE TITLE
Enforce arrow-callbacks

### ISSUE THREAD

**Issue by jbalsas** [liferay/eslint-config-liferay#67]
Now that we've successfully enabled js transpilation for both new and legacy code... would we want to setup [prefer-arrow-callback](https://eslint.org/docs/rules/prefer-arrow-callback) to enforce this somehow?

From https://github.com/jbalsas/liferay-portal/pull/1872/files#diff-65cecb658d96c7d1f29a6ba61f1001dbR103

**Comment by wincent** [comment]
I think in most cases arrow functions make for better callbacks, so I'd be in favor of adding this rule. The fact that it only concerns itself with functions in "callback" positions means it is less likely to cause problems (ie. you can still write `const x = function blah() { };` if you really want).

About the only cases where they aren't better is where you have a good reason for wanting a named function (rare: you might expect it to show up in a stacktrace, and if we want to allow that we can use `allowNamedFunctions: true`).

**Comment by jbalsas** [comment]
See https://github.com/liferay/eslint-config-liferay/pull/87

**Comment by wincent** [comment]
Merged: https://github.com/liferay/eslint-config-liferay/pull/87
