### ISSUE TITLE
Sort imports

### ISSUE THREAD

**Issue by wincent** [liferay/eslint-config-liferay#70]
We would like to sort imports automatically, so creating this ticket for *enforcement*.

We also have [this liferay-frontend-guidelines ticket for *documenting* how imports should be sorted](https://github.com/liferay/liferay-frontend-guidelines/issues/60).

See also [latest example](https://github.com/brianchandotcom/liferay-portal/pull/77123#issuecomment-5224320190) of this coming up.

**Comment by jbalsas** [comment]
I was doing some research on this... it feels like the most widely used imports plugin for eslint is [eslint-plugin-imports](https://www.npmjs.com/package/eslint-plugin-import).

weekly downloads | last publish | license | contributors | used by
--- | --- | --- | --- | ---
4,582,919 | a month ago | MIT | 153 | 1,433,869 repos

It supports [group-based ordering](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md) of imports and support for rhs alphabetization is up for review at https://github.com/benmosher/eslint-plugin-import/pull/1360
